name: "Pull Request"

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  pull_request:
    name: "Lint and Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v7.0.1"

      - name: "Set up Python"
        uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.14"
          cache: "pip"

      - name: "Install requirements"
        run: |
          python3 -m pip install uv &&
          uv venv &&
          uv pip install -r requirements.txt

      - name: "Lint"
        run: uv run python -m ruff check

      - name: "Test"
        run: uv run python -m unittest discover -v
